/*
 * This source file was generated by the Gradle 'init' task
 */
package junit;

public class Calculadora {

    public int sumar(int a, int b) {
        return a + b;
    }
    
    public int restar(int a, int b) {
        return a - b;
    }
    }
